
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootpassword # <-- change if needed
  MYSQL_DATABASE: micro_db # <-- change if needed
  MYSQL_USER: micro_user # <-- change if needed
  MYSQL_PASSWORD: secret # <-- change if needed

