apiVersion: batch/v1
kind: Job
metadata:
  name: create-mysql-secret
  namespace: default
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: create-secret
        image: bitnami/kubectl:latest
        command: ["/bin/sh", "-c"]
        args:
          - |
            kubectl delete secret mysql-secret --ignore-not-found
            kubectl create secret generic mysql-secret \
              --from-literal=MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD} \
              --from-literal=MYSQL_DATABASE=${MYSQL_DATABASE} \
              --from-literal=MYSQL_USER=${MYSQL_USER} \
              --from-literal=MYSQL_PASSWORD=${MYSQL_PASSWORD}
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: github-org-secrets
                key: MYSQL_ROOT_PASSWORD
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: github-org-secrets
                key: MYSQL_DATABASE
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: github-org-secrets
                key: MYSQL_USER
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: github-org-secrets
                key: MYSQL_PASSWORD
