apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: expense-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/exp-track-org/expense-service.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
