apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/exp-track-org/infra.git

    targetRevision: main
    path: cluster-resources
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

