apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:       # <-- change this path if you want a different folder on EC2
    path: /mnt/data/mysql
  persistentVolumeReclaimPolicy: Retain

