# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: infra-app
#   namespace: argocd
# spec:
#   project: default
#   source:
#     repoURL: 'https://github.com/exp-tracker-org/infra.git'
#     targetRevision: main
#     path: '.'
#     kustomize: {} 
#     directory:
#       recurse: true
#   destination:
#     server: 'https://kubernetes.default.svc'
#     namespace: default
#   syncPolicy:
#     automated:
#       prune: true       # delete resources removed from Git
#       selfHeal: true    # auto-fix drift
#     syncOptions:
#       - CreateNamespace=true
#   hooks:
#     # Pre-sync hook for MySQL secret
#     - exec:
#         command: ["kubectl", "apply", "-f", "pre-sync-hooks/create-mysql-secret.yaml"]
#         hookType: PreSync
#   ignoreDifferences:
#     - group: ""
#       kind: ConfigMap
#       name: mysql-config
#       jsonPointers:
#         - /data

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0" 
spec:
  project: default
  source:
    repoURL: 'https://github.com/exp-tracker-org/infra.git'
    targetRevision: main
    path: '.'
    #kustomize: {}        # 👈 use kustomize, not directory.recurse
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: ""
      kind: ConfigMap
      name: mysql-config
      jsonPointers:
        - /data

