apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0" 
spec:
  project: default
  source:
    repoURL: 'https://github.com/exp-tracker-org/infra.git'
    targetRevision: main
    path: '.'
    kustomize: {}       
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: ""
      kind: ConfigMap
      name: mysql-config
      jsonPointers:
        - /data

